name: Binaries Release

on:
  release:
    types: [created]

jobs:
  compile:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm run build:executable
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./natives/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true