name: Binaries Release

on:
  release:
    types: [created]

jobs:
  compile:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm run build:executable
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@133984371c30d34e38222a64855679a414cb7575 # tag=v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./natives/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true